title: Alauda Streaming Service for Kafka
logoText: Alauda Streaming Service for Kafka
lang: zh
api:
  crds:
    - docs/shared/crds/*.yaml
  openapis:
    - docs/shared/openapis/*.json
permission:
  functionresources:
    - docs/shared/functionresources/*.yaml
  roletemplates:
    - docs/shared/roletemplates/*.yaml
releaseNotes:
  queryTemplates:
    mw-kafka-v4.0-fixed: |
      project = MiddleWare AND feature = "MiddleWare - Kafka" AND type = Bug AND affectedVersion not in (v4.0.0) AND fixVersion in (v4.0.0) AND status in (Resolved, 已验证) AND ReleaseNotesStatus = Publish ORDER BY priority DESC
    mw-kafka-v4.0-known: |
      project = MiddleWare AND feature = "MiddleWare - Kafka" AND type = Bug AND labels in (v4.0.0-RN) AND ReleaseNotesStatus = Publish ORDER BY priority DESC
