spring:
  kafka:
    security:
      protocol: SSL
    ssl:
      trust-store-type: PKCS12
      trust-store-location: file:${KAFKA_TRUSTSTORE_PATH}
      trust-store-password: ${KAFKA_TRUSTSTORE_PASSWORD}
      key-store-type: PKCS12
      key-store-location: file:${KAFKA_KEYSTORE_PATH}
      key-store-password: ${KAFKA_KEYSTORE_PASSWORD}
